apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: slides-demo
servers: 1
agents: 0
ports:
  - port: 80:80
    nodeFilters: [loadbalancer]
  - port: 443:443
    nodeFilters: [loadbalancer]
registries:
  create:
    name: slides-registry
    host: "0.0.0.0"
    hostPort: "5050"
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters: [server:0]
