#!/usr/bin/env bash
# Publishes the generated export assets to a GitHub release tag, so that
# `make -C export pptx` works on a fresh clone (and in CI) without a cluster.
#
# Flat asset names encode their directory: assets/stills/x.png -> stills-x.png
# (see fetch-assets.mjs). Re-running overwrites the existing assets in place.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DIST="${ROOT}/export/dist"
TAG="${EXPORT_ASSET_TAG:-export-v1}"

command -v gh >/dev/null || { echo "gh CLI is required to publish assets" >&2; exit 1; }

staging="${DIST}/publish"
rm -rf "${staging}"
mkdir -p "${staging}"

shopt -s nullglob
for f in "${DIST}"/assets/stills/*.png; do cp "${f}" "${staging}/stills-$(basename "${f}")"; done
for f in "${DIST}"/assets/screens/*.png; do cp "${f}" "${staging}/screens-$(basename "${f}")"; done
shopt -u nullglob

count=$(find "${staging}" -name '*.png' | wc -l)
[[ "${count}" -gt 0 ]] || { echo "no assets in ${DIST}/assets to publish" >&2; exit 1; }

echo "==> Publishing ${count} assets to release ${TAG}"
if gh release view "${TAG}" >/dev/null 2>&1; then
  gh release upload "${TAG}" "${staging}"/*.png --clobber
else
  gh release create "${TAG}" "${staging}"/*.png \
    --title "Deck export assets (${TAG})" \
    --notes "Diagram stills and demo screenshots used to build the offline .pptx export. Generated by export/scripts (see docs/adrs/006-presentation-export.md)."
fi

rm -rf "${staging}"
echo "==> Done"
