apiVersion: presentations.haavard.dev/v1alpha1
kind: Presentation
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/managed-by: kustomize
  name: presentation-sample
spec:
  theme:
    logo: "https://...."
    primaryColor: "#000000"
    secondaryColor: "#FFFFFF"
  slides:
    - title: "initial title"
      bullets:
        - "first bullet"
        - "another bullet"
      images:
        - "https://"
        - "https://..."
